# syntax=docker/dockerfile:1
FROM frappe/erpnext:latest

USER frappe

# Copy foundry_erp app to apps directory
COPY --chown=frappe:frappe ./foundry_erp /home/frappe/frappe-bench/apps/foundry_erp

# Install foundry_erp app as Python package
RUN cd /home/frappe/frappe-bench/apps/foundry_erp && \
    /home/frappe/frappe-bench/env/bin/pip install -e .

# Add foundry_erp to apps.txt
RUN echo "foundry_erp" >> /home/frappe/frappe-bench/sites/apps.txt

WORKDIR /home/frappe/frappe-bench

USER frappe
